'use client';
import {useEffect,useRef,useState} from 'react';
import {supabase} from '../lib/supabase';
type Sale={id:string;version:number;reference:string;customer_id:string;contact_name:string;phone:string;campaign_id:string|null;campaign_name:string|null;amount:number|null;purchased_on:string|null;notes:string|null;voided:boolean};
type Contact={id:string;name:string;phone:string};
const money=(v:number|null)=>v===null?'Não informado':Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export default function SalesPanel({org,campaigns,onSaved,refreshVersion}:{org:string;campaigns:{id:string;name:string}[];onSaved:()=>void;refreshVersion:number}){
 const [rows,setRows]=useState<Sale[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(0),[filter,setFilter]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[open,setOpen]=useState(false),[editing,setEditing]=useState<Sale|null>(null),[contacts,setContacts]=useState<Contact[]>([]),[search,setSearch]=useState(''),[customer,setCustomer]=useState(''),[picked,setPicked]=useState<Contact|null>(null),[campaign,setCampaign]=useState('');
 const saving=useRef(false);
 async function load(){if(!supabase)return;const r=await supabase.rpc('list_sales',{org,page_number:page,campaign_filter:filter||null});if(r.error)throw new Error(r.error.message);setRows(r.data.rows);setTotal(Number(r.data.total));}
 useEffect(()=>{let active=true;supabase?.rpc('list_sales',{org,page_number:page,campaign_filter:filter||null}).then(({data,error})=>{if(!active)return;if(error)setError(error.message);else{setRows(data.rows);setTotal(Number(data.total));setError('')}});return()=>{active=false}},[org,page,filter,refreshVersion]);
 useEffect(()=>{if(!open)return;let active=true;const timer=setTimeout(()=>{supabase?.rpc('browse_contacts',{org,query:search,page_size:20,sort_field:'name',ascending:true}).then(({data,error})=>{if(!active)return;if(error)setError(error.message);else setContacts(data.rows)})},250);return()=>{active=false;clearTimeout(timer)}},[open,search,org]);
 function edit(s:Sale|null,defaultCampaign=''){setError('');setEditing(s);setCustomer(s?.customer_id??'');setPicked(s?{id:s.customer_id,name:s.contact_name,phone:s.phone}:null);setCampaign(s?.campaign_id??defaultCampaign);setSearch('');setContacts([]);setOpen(true);}
 return <section className="panel"><div className="toolbar"><div><h2>Registro manual de vendas</h2><p>Registre a venda e escolha a campanha que originou a compra.</p></div><button onClick={()=>edit(null,filter)}>Registrar venda</button></div><label>Filtrar por campanha<select value={filter} onChange={e=>{setFilter(e.target.value);setPage(0)}}><option value="">Todas</option>{campaigns.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label>{error&&<p className="alert" role="alert">{error}</p>}<div className="table-wrap"><table><thead><tr>{['Referência','Contato','Campanha','Valor','Data da venda','Situação','Ações'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{rows.map(s=><tr key={s.id}><td>{s.reference}</td><td>{s.contact_name}<br/><small>{s.phone}</small></td><td>{s.campaign_name??'Sem campanha'}</td><td>{money(s.amount)}</td><td>{s.purchased_on?s.purchased_on.split('-').reverse().join('/'):'Não informada'}</td><td>{s.voided?'Cancelada':'Registrada'}</td><td><button className="link" onClick={()=>edit(s)}>Editar</button></td></tr>)}</tbody></table></div>{!rows.length&&<p>Nenhuma venda encontrada.</p>}<div className="toolbar"><span>{total} vendas · página {page+1}</span><button className="secondary" disabled={page===0} onClick={()=>setPage(page-1)}>Anterior</button><button className="secondary" disabled={(page+1)*20>=total} onClick={()=>setPage(page+1)}>Próxima</button></div><p>Este registro não recalcula Total Comprado ou Número de Pedidos do contato: esses campos podem incluir compras anteriores que não estão nesta lista.</p>
 {open&&<div className="overlay"><section className="dialog" role="dialog" aria-modal="true" aria-label={editing?'Editar venda':'Registrar venda'}><div className="toolbar"><h2>{editing?'Editar venda':'Registrar venda'}</h2><button className="secondary" disabled={busy} onClick={()=>setOpen(false)}>Fechar</button></div><form key={editing?.id??'new'} onSubmit={async e=>{e.preventDefault();if(saving.current||!supabase)return;const f=new FormData(e.currentTarget);saving.current=true;setBusy(true);setError('');try{const r=await supabase.rpc('save_sale',{org,sale:editing?.id??null,expected_version:editing?.version??null,data:{reference:String(f.get('reference')).trim(),customer_id:customer,campaign_id:campaign||null,amount:f.get('amount')===''?null:Number(f.get('amount')),purchased_on:f.get('purchased_on')||null,notes:f.get('notes')||null,voided:f.get('voided')==='on'}});if(r.error)throw new Error(r.error.message);setOpen(false);await load();onSaved()}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar a venda.')}finally{saving.current=false;setBusy(false)}}}>
 <label>Referência da venda<input name="reference" required defaultValue={editing?.reference??crypto.randomUUID()} placeholder="Número do pedido ou identificador único"/><small>Não repita a referência de outra venda. Ela evita duplicidade na sincronização.</small></label><label>Buscar contato<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nome ou telefone"/></label><label>Contato<select required value={customer} onChange={e=>{setCustomer(e.target.value);setPicked(contacts.find(c=>c.id===e.target.value)??picked)}}><option value="">Selecione</option>{picked&&!contacts.some(c=>c.id===picked.id)&&<option value={picked.id}>{picked.name} · {picked.phone}</option>}{contacts.map(c=><option value={c.id} key={c.id}>{c.name} · {c.phone}</option>)}</select></label><label>Campanha<select value={campaign} onChange={e=>setCampaign(e.target.value)}><option value="">Sem campanha vinculada</option>{campaigns.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><div className="form-grid"><label>Valor opcional<input name="amount" type="number" min="0" step="0.01" defaultValue={editing?.amount??''}/></label><label>Data da venda opcional<input name="purchased_on" type="date" max={new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo'}).format(new Date())} defaultValue={editing?.purchased_on??''}/></label></div><label>Observações<textarea name="notes" defaultValue={editing?.notes??''}/></label><label className="check"><input type="checkbox" name="voided" defaultChecked={editing?.voided??false}/>Venda cancelada</label><p>Vendas canceladas preservam o histórico e não entram nos indicadores da campanha.</p><button disabled={busy}>{busy?'Salvando…':'Salvar venda'}</button></form>{error&&<p className="alert" role="alert">{error}</p>}</section></div>}</section>;
}
